### ISSUE TITLE
How to get a client?

### ISSUE THREAD

**Issue by xyebizz** [ropiku/omniauth-instagram#13]
Hi! 

Sorry for a stupid question,
previously I used omniauth-twtter and passed configurations like this:

client = Twitter::REST::Client.new do |config|
  config.consumer_key        = "YOUR_CONSUMER_KEY"
  config.consumer_secret     = "YOUR_CONSUMER_SECRET"
  config.access_token        = "YOUR_ACCESS_TOKEN"
  config.access_token_secret = "YOUR_ACCESS_SECRET"
end

and then I used it like client.user("gem")

How can I get the same thing with omniauth-instagram?

Thanks!

**Comment by ropiku** [comment]
The client has nothing to do with Omniauth, that's for authenticating users. What you described is the [twitter](https://github.com/sferik/twitter) gem.
Take a look at the [instagram-ruby-gem](https://github.com/Instagram/instagram-ruby-gem) if you need an Instagram client.
