### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by rizalmuthi** [ropiku/omniauth-instagram#15]
Is there anyway that we can specify the scope of the authentication?

Thanks

**Comment by ksylvest** [comment]
+1

**Comment by ksylvest** [comment]
Pretty trivial: https://github.com/ropiku/omniauth-instagram/pull/18. Is this library still maintained at all?

**Comment by ropiku** [comment]
I merged #18. I haven't used this library in a long time and I don't maintain it. Happy to pass it on if you want to work on it.
